name: Latest Release
on:
  push:
    branches: ["ci-toolboxes"]

jobs:
  package:
    name: Package toolbox
    env:
      snapshot_version: v1.5.0
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest-including-prerelease
          products: >
            Mapping_Toolbox
            Image_Processing_Toolbox
            MATLAB_Coder
      - name: Cache snapshot data
        id: cache-snapshots
        uses: actions/cache@v4
        with:
          path: tests/snapshots/data
          key: snapshots-${{ env.snapshot_version }}
      - name: Download and extract snapshot data
        if: steps.cache-snapshots.outputs.cache-hit != 'true'
        working-directory: tests/snapshots
        shell: bash
        run: |
          curl -L -o snapshot_data.tar.gz \
          "https://github.com/TopoToolbox/snapshot_data/releases/download/$snapshot_version/snapshot_data.tar.gz"
          tar -xzf snapshot_data.tar.gz
      - name: Verify snapshot data
        working-directory: tests/snapshots
        shell: bash
        if: ${{ matrix.os != 'windows-latest' }}
        run:
          shasum -c --status sha256sum.txt
      - name: Start virtual display server
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Compile libtopotoolbox and MEX files
        uses: matlab-actions/run-build@v2
        with:
          tasks: compile
      - name: Build docs
        uses: matlab-actions/run-build@v2
        with:
          tasks: doc
      - name: Build package
        uses: matlab-actions/run-build@v2
        with:
          tasks: package
      - name: Upload toolbox as artifact
        uses: actions/upload-artifact@v4
        with:
          name: toolbox-${{ matrix.os }}
          path: release/TopoToolbox_*.mltbx
